### ISSUE TITLE
Plain Text format dump support

### ISSUE THREAD

**Issue by Worschi** [gmr/pgdumplib#10]
I need to parse plain text dump files and would like to use pgdumplib as a more generic solution compared to my parser.

**Comment by gmr** [comment]
Those are just raw SQL statements. There are a few libraries for that:

- https://pypi.org/project/pgparse/
- https://pypi.org/project/pglast/

(And a few more)

**Comment by Worschi** [comment]
thanks for pointing out the libraries. Somehow obvious that there are raw SQL parsers. didn't cross my mind though. thanks!
