### ISSUE TITLE
Python 3.6 incompatibility

### ISSUE THREAD

**Issue by AlexisBRENON** [gmr/pgdumplib#9]
This package is not compatible with any Python version < 3.7.

Trying to load a dump raise the following exception:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../.venv/lib/python3.6/site-packages/pgdumplib/__init__.py", line 22, in load
    from pgdumplib import dump
  File "....venv/lib/python3.6/site-packages/pgdumplib/dump.py", line 24
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined
```

I tried all major versions (1.0.1, 2.1.0 and 3.1.0).

Is there a way to make it compatible ? Else you should mark the package with a [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires).

**Comment by gmr** [comment]
No, I'm not supporting anything < 3.7. The trove classifiers and pypi index clearly spell that out:

https://github.com/gmr/pgdumplib/blob/master/setup.cfg#L17
https://pypi.org/project/pgdumplib
